import type { DemoLoader } from "./types";

export const demoRegistry: Record<string, DemoLoader> = {
  "material-lighting": {
    definition: {
      slug: "material-lighting",
      maturity: "completed",
      evidence: "verified",
      backend: "three-webgpu",
      backends: ["three-webgpu", "three-webgl", "canvas-2d"],
      capabilities: ["webgpu", "webgl2"],
      requirements: [
        "WebGPU preferred",
        "WebGL2 automatic fallback",
        "Canvas fallback on renderer failure",
      ],
      fallbackImage: "/media/demos/material-lighting-poster.svg",
      relatedProjects: ["real-time-rendering-lab"],
      relatedArticles: ["rhi-abstraction-boundaries"],
      metricSources: ["animation-frame"],
    },
    load: () => import("../material-lighting"),
  },
  "render-graph": {
    definition: {
      slug: "render-graph",
      maturity: "completed",
      evidence: "measured",
      backend: "svg",
      backends: ["svg"],
      capabilities: [],
      requirements: ["Baseline DOM and SVG"],
      fallbackImage: "/media/demos/render-graph-poster.svg",
      relatedProjects: ["engine-systems-explorer"],
      relatedArticles: ["render-graph-lifetime"],
      metricSources: ["cpu-wall-clock"],
    },
    load: () => import("../render-graph"),
  },
  "gpu-particles": {
    definition: {
      slug: "gpu-particles",
      maturity: "completed",
      evidence: "measured",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU", "timestamp-query optional"],
      fallbackImage: "/media/demos/gpu-particles-poster.svg",
      relatedProjects: ["webgpu-compute-lab"],
      relatedArticles: ["compute-geometry-performance", "webgpu-particles-path-tracing"],
      metricSources: ["gpu-timestamp-query", "animation-frame"],
    },
    load: () => import("../gpu-particles"),
  },
  "shadow-aa": {
    definition: {
      slug: "shadow-aa",
      maturity: "completed",
      evidence: "verified",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU preferred", "Canvas static fallback"],
      fallbackImage: "/media/demos/shadow-aa-poster.svg",
      relatedProjects: ["real-time-rendering-lab"],
      relatedArticles: ["rhi-abstraction-boundaries"],
      metricSources: ["animation-frame", "unavailable"],
    },
    load: () => import("../shadow-aa"),
  },
  "path-tracer": {
    definition: {
      slug: "path-tracer",
      maturity: "completed",
      evidence: "verified",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU", "rgba16float storage texture"],
      fallbackImage: "/media/demos/path-tracer-poster.svg",
      relatedProjects: ["webgpu-compute-lab"],
      relatedArticles: ["webgpu-particles-path-tracing", "path-tracing-to-neural-denoising"],
      metricSources: ["animation-frame"],
    },
    load: () => import("../path-tracer"),
  },
  "frame-inspector": {
    definition: {
      slug: "frame-inspector",
      maturity: "completed",
      evidence: "verified",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU preferred", "Canvas attachment atlas fallback"],
      fallbackImage: "/media/demos/frame-inspector-poster.svg",
      relatedProjects: ["engine-systems-explorer"],
      relatedArticles: ["render-graph-lifetime"],
      metricSources: ["unavailable"],
    },
    load: () => import("../frame-inspector"),
  },
  "neural-denoising": {
    definition: {
      slug: "neural-denoising",
      maturity: "completed",
      evidence: "measured",
      backend: "onnx-web",
      backends: ["onnx-web", "canvas-2d"],
      capabilities: ["webgpu", "wasm"],
      requirements: ["Explicit model run", "WebGPU optional", "single-thread WASM fallback"],
      fallbackImage: "/media/demos/neural-denoising-poster.svg",
      relatedProjects: ["neural-graphics-lab"],
      relatedArticles: ["path-tracing-to-neural-denoising"],
      metricSources: ["inference-end-to-end", "unavailable"],
    },
    load: () => import("../neural-denoising"),
  },
};

export type DemoSlug = keyof typeof demoRegistry;
