import type { DemoLoader } from "./types";

export const demoRegistry: Record<string, DemoLoader> = {
  "material-lighting": {
    definition: {
      slug: "material-lighting",
      maturity: "completed",
      evidence: "verified",
      backend: "three-webgpu",
      backends: ["three-webgpu", "three-webgl", "canvas-2d"],
      capabilities: ["webgpu", "webgl2"],
      requirements: [
        "WebGPU preferred",
        "WebGL2 automatic fallback",
        "Canvas fallback on renderer failure",
      ],
      fallbackImage: "/media/demos/material-lighting-poster.svg",
      relatedProjects: ["real-time-rendering-lab"],
      relatedArticles: ["material-lighting-color-pipeline"],
      metricSources: ["animation-frame"],
      assetIds: ["calibration-rig"],
      modes: ["pbr-calibration", "debug-view"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/material-lighting.ts",
      referenceScene: "calibration-rig",
    },
    load: () => import("../material-lighting"),
  },
  "clustered-lighting": {
    definition: {
      slug: "clustered-lighting",
      maturity: "completed",
      evidence: "measured",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU preferred", "timestamp-query optional", "Canvas fallback"],
      fallbackImage: "/media/demos/clustered-lighting-poster.svg",
      relatedProjects: ["real-time-rendering-lab"],
      relatedArticles: ["clustered-deferred-lighting", "frame-inspector-observability"],
      metricSources: ["gpu-timestamp-query", "cpu-wall-clock"],
      assetIds: ["research-courtyard"],
      modes: ["naive", "deferred", "clustered"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/clustered-lighting.ts",
      referenceScene: "research-courtyard",
    },
    load: () => import("../clustered-lighting"),
  },
  "render-graph": {
    definition: {
      slug: "render-graph",
      maturity: "completed",
      evidence: "measured",
      backend: "svg",
      backends: ["svg"],
      capabilities: [],
      requirements: ["Baseline DOM and SVG"],
      fallbackImage: "/media/demos/render-graph-poster.svg",
      relatedProjects: ["engine-systems-explorer"],
      relatedArticles: [
        "render-graph-lifetime",
        "rhi-abstraction-boundaries",
        "frame-inspector-observability",
      ],
      metricSources: ["cpu-wall-clock"],
      assetIds: [],
      modes: ["compiler"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/render-graph.ts",
    },
    load: () => import("../render-graph"),
  },
  "gpu-particles": {
    definition: {
      slug: "gpu-particles",
      maturity: "completed",
      evidence: "measured",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU", "timestamp-query optional"],
      fallbackImage: "/media/demos/gpu-particles-poster.svg",
      relatedProjects: ["webgpu-compute-lab"],
      relatedArticles: [
        "compute-geometry-performance",
        "webgpu-particles-path-tracing",
        "gpu-driven-visibility-indirect",
      ],
      metricSources: ["gpu-timestamp-query", "animation-frame"],
      assetIds: ["research-courtyard"],
      modes: ["simulation", "visibility"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/gpu-particles.ts",
      referenceScene: "research-courtyard",
    },
    load: () => import("../gpu-particles"),
  },
  "shadow-aa": {
    definition: {
      slug: "shadow-aa",
      maturity: "completed",
      evidence: "verified",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU preferred", "Canvas static fallback"],
      fallbackImage: "/media/demos/shadow-aa-poster.svg",
      relatedProjects: ["real-time-rendering-lab"],
      relatedArticles: ["shadow-temporal-aa", "frame-inspector-observability"],
      metricSources: ["animation-frame", "unavailable"],
      assetIds: ["research-courtyard"],
      modes: ["shadow", "temporal"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/shadow-aa.ts",
      referenceScene: "research-courtyard",
    },
    load: () => import("../shadow-aa"),
  },
  "path-tracer": {
    definition: {
      slug: "path-tracer",
      maturity: "completed",
      evidence: "verified",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU", "rgba16float storage texture"],
      fallbackImage: "/media/demos/path-tracer-poster.svg",
      relatedProjects: ["webgpu-compute-lab"],
      relatedArticles: ["webgpu-particles-path-tracing", "bvh-progressive-path-tracing"],
      metricSources: ["animation-frame"],
      assetIds: ["cornell-scene"],
      modes: ["progressive"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/path-tracer.ts",
      referenceScene: "cornell",
    },
    load: () => import("../path-tracer"),
  },
  "frame-inspector": {
    definition: {
      slug: "frame-inspector",
      maturity: "completed",
      evidence: "verified",
      backend: "raw-webgpu",
      backends: ["raw-webgpu", "canvas-2d"],
      capabilities: ["webgpu"],
      requirements: ["WebGPU preferred", "Canvas attachment atlas fallback"],
      fallbackImage: "/media/demos/frame-inspector-poster.svg",
      relatedProjects: ["engine-systems-explorer", "real-time-rendering-lab"],
      relatedArticles: [
        "render-graph-lifetime",
        "frame-inspector-observability",
        "shadow-temporal-aa",
        "rhi-abstraction-boundaries",
        "clustered-deferred-lighting",
      ],
      metricSources: ["unavailable"],
      assetIds: ["research-courtyard"],
      modes: ["attachments", "probe"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/frame-inspector.ts",
      referenceScene: "research-courtyard",
    },
    load: () => import("../frame-inspector"),
  },
  "neural-denoising": {
    definition: {
      slug: "neural-denoising",
      maturity: "in-progress",
      evidence: "measured",
      backend: "onnx-web",
      backends: ["onnx-web", "canvas-2d"],
      capabilities: ["webgpu", "wasm"],
      requirements: ["Explicit model run", "WebGPU optional", "single-thread WASM fallback"],
      fallbackImage: "/media/demos/neural-denoising-poster.svg",
      relatedProjects: ["neural-graphics-lab"],
      relatedArticles: ["path-tracing-to-neural-denoising"],
      metricSources: ["inference-end-to-end", "unavailable"],
      assetIds: ["neural-heldout-v2"],
      modes: ["rgb", "guided"],
      sourceUrl:
        "https://github.com/yzscodehub/graphics-portfolio/blob/main/src/demos/neural-denoising.ts",
    },
    load: () => import("../neural-denoising"),
  },
};

export type DemoSlug = keyof typeof demoRegistry;
